# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  docscheduler-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: docscheduler-mysql
    volumes:
      - docscheduler-mysql-data:/var/lib/mysql
    ports:
      - "3336:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docscheduler
      - MYSQL_DATABASE=doctor_scheduler
      - MYSQL_USER=docscheduler
      - MYSQL_PASSWORD=docscheduler

  # PHP (with nginx)
  app:
    image: ambientum/php:7.0-nginx
    container_name: docscheduler-app
    volumes:
      - .:/var/www/app
    ports:
      - "8008:8080"
    links:
      - mysql